version: '3.9'

services:
  bot:
    build: .
    command: python -m src.main
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CHECK_INTERVAL=${CHECK_INTERVAL:-5}
    depends_on:
      - redis

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A src.tasks beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CHECK_INTERVAL=${CHECK_INTERVAL:-5}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6380:6379" 